apiVersion: v2
name: otel-add-on
description: A Helm chart for KEDA otel-add-on
type: application
version: v0.0.1-0
appVersion: v0.0.1-0
kubeVersion: ">= 1.19.0-0"
icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
dependencies:
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.108.0
    condition: opentelemetry-collector.enabled
home: https://github.com/kedify/otel-add-on
sources:
  - https://github.com/kedify/otel-add-on
  - https://github.com/open-telemetry/opentelemetry-helm-charts
annotations:
  artifacthub.io/category: networking
  artifacthub.io/links: |
    - name: gh repo
      url: https://github.com/kedify/otel-add-on
    - name: helm repo
      url: https://kedify.github.io/otel-add-on
  artifacthub.io/images: |
    - name: scaler
      image: ghcr.io/kedify/otel-add-on
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/license: Apache-2.0
