apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: podinfo-pull-example
spec:
  scaleTargetRef:
    name: podinfo
  triggers:
    - type: external
      metadata:
        scalerAddress: "keda-otel-scaler.keda.svc:4318"
        metricQuery: "avg(http_request_duration_seconds_count{method=GET, status=200})"
        operationOverTime: "rate"
        targetValue: "2"
        clampMax: "600"
  minReplicaCount: 1
  maxReplicaCount: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
        scaleUp:
          stabilizationWindowSeconds: 0
