{{- if and .Values.otelOperator.enabled .Values.otelOperatorCr.create }}
{{- if .Values.otelOperatorCr.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.otelOperatorCr.serviceAccount.name | default (include "otel-add-on.name" .) }}
  namespace: {{ .Values.otelOperatorCr.namespace | default .Release.Namespace }}
  labels:
    {{- include "otel-add-on.labels" . | nindent 4 }}
  {{- with .Values.otelOperatorCr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
{{- end }}
{{- if and .Values.otelOperatorCr.clusterRole.create .Values.otelOperatorCr.clusterRole.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "otel-add-on.name" . }}
  labels:
    {{- include "otel-add-on.labels" . | nindent 4 }}
  {{- with .Values.otelOperatorCr.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
rules:
{{- toYaml .Values.otelOperatorCr.clusterRole.rules | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.otelOperatorCr.serviceAccount.name | default (include "otel-add-on.name" .) }}
  labels:
    {{- include "otel-add-on.labels" . | nindent 4 }}
  {{- with .Values.otelOperatorCr.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "otel-add-on.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.otelOperatorCr.serviceAccount.name | default (include "otel-add-on.name" .) }}
  namespace: {{ .Values.otelOperatorCr.namespace | default .Release.Namespace }}
{{- end }}
{{- end }}
