{{- range include "operatorCrs" . | fromJsonArray }}

{{- if .serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name | default (printf "%s-op" $.Release.Name) }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
{{- end }}

{{- if and .clusterRole.create .clusterRole.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .serviceAccount.name | default (printf "%s-op" $.Release.Name) }}
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
  {{- with .clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
rules:
{{- toYaml .clusterRole.rules | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .serviceAccount.name | default (printf "%s-op" $.Release.Name) }}
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
  {{- with .clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .serviceAccount.name | default $.Release.Name }}
subjects:
- kind: ServiceAccount
  name:  {{ .serviceAccount.name | default $.Release.Name }}
  namespace:  {{ .namespace | default $.Release.Namespace }}
{{- end }}

{{- if and .targetAllocatorEnabled (.targetAllocator).serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .targetAllocator.serviceAccount }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
{{- $crScope := . -}}
{{- range .targetAllocatorClusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ . }}-otc
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $crScope.targetAllocator.serviceAccount }}
    namespace: {{ $crScope.namespace | default $.Release.Namespace }}
{{- end }}
{{- end }}

{{- end }}
