{{- range $i, $c := include "operatorCrs" . | fromJsonArray }}
{{- if $c.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $c.serviceAccount.name | default $.Values.fullnameOverride | default (printf "%s-op-%d" $.Release.Name $i) }}
  namespace: {{ $c.namespace | default $.Release.Namespace }}
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
  {{- with $c.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
{{- end }}

{{- if and $c.clusterRole.create $c.clusterRole.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $c.serviceAccount.name | default $.Values.fullnameOverride | default (printf "%s-op-%d" $.Release.Name $i) }}
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
  {{- with $c.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
rules:
{{- toYaml $c.clusterRole.rules | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $c.serviceAccount.name | default $.Values.fullnameOverride | default (printf "%s-op-%d" $.Release.Name $i) }}
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
  {{- with $c.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $c.serviceAccount.name | default $.Values.fullnameOverride | default (printf "%s-op-%d" $.Release.Name $i) }}
subjects:
- kind: ServiceAccount
  name:  {{ $c.serviceAccount.name | default $.Values.fullnameOverride | default (printf "%s-op-%d" $.Release.Name $i) }}
  namespace:  {{ $c.namespace | default $.Release.Namespace }}
{{- end }}

{{- if and $c.targetAllocatorEnabled ($c.targetAllocator).serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $c.targetAllocator.serviceAccount }}
  namespace: {{ $c.namespace | default $.Release.Namespace }}
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
  {{- with $c.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
{{- range $c.targetAllocatorClusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ . }}-otc
  labels:
    {{- include "otel-add-on.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $c.targetAllocator.serviceAccount }}
    namespace: {{ $c.namespace | default $.Release.Namespace }}
{{- end }}
{{- end }}

{{- end }}
