{{- if (include "atLeastOneOperatorCr" $) -}}
# minimal rbac for post-install jop that creates scaled object for interceptor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manipulate-otc
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade,pre-delete"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manipulate-otc
  annotations:
    helm.sh/hook: "post-install,post-upgrade,pre-delete"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
rules:
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manipulate-otc
  annotations:
    helm.sh/hook: "post-install,post-upgrade,pre-delete"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manipulate-otc
subjects:
- kind: ServiceAccount
  name: manipulate-otc
  namespace: {{ .Release.Namespace }}
{{- end }}
