{{- if and .Values.otelOperator.enabled .Values.otelOperatorCr.create }}
# minimal rbac for post-install jop that creates scaled object for interceptor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: install-otc
  namespace: {{ .Values.otelOperatorCr.namespace | default .Release.Namespace }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: install-otc
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
rules:
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors
  verbs:
  - patch
  - create
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: install-otc
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: install-otc
subjects:
- kind: ServiceAccount
  name: install-otc
  namespace: {{ .Values.otelOperatorCr.namespace | default .Release.Namespace }}
{{- end }}
