{{- if .Values.deployScaler }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "otel-add-on.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otel-add-on.selectorLabels" . | nindent 6 }}
  {{- if eq .Values.deploymentStrategy "Recreate" }}
  strategy:
    type: Recreate
  {{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "otel-add-on.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Ports
            - name: OTLP_RECEIVER_PORT
              value: {{ .Values.service.otlpReceiverPort | quote }}
            - name: KEDA_EXTERNAL_SCALER_PORT
              value: {{ .Values.service.kedaExternalScalerPort | quote }}
            - name: INTERNAL_METRICS_PORT
              value: {{ .Values.settings.internalMetricsPort | quote }}
            - name: REST_API_PORT
              value: {{ .Values.settings.restApiPort | quote }}

            # Metric Store
            - name: METRIC_STORE_RETENTION_SECONDS
              value: {{ .Values.settings.metricStore.retentionSeconds | quote }}
            - name: METRIC_STORE_LAZY_SERIES
              value: {{ .Values.settings.metricStore.lazySeries | quote }}
            - name: METRIC_STORE_LAZY_AGGREGATES
              value: {{ .Values.settings.metricStore.lazyAggregates | quote }}
            - name: METRIC_STORE_ERROR_IF_NOT_FOUND
              value: {{ .Values.settings.metricStore.errIfNotFound | quote }}
            - name: METRIC_STORE_VALUE_IF_NOT_FOUND
              value: {{ .Values.settings.metricStore.valueIfNotFound | quote }}
            - name: IS_ACTIVE_POLLING_INTERVAL_MS
              value: {{ .Values.settings.isActivePollingIntervalMilliseconds | quote }}

            # TLS OTLP
            - name: OTLP_TLS_CA_FILE
              value: {{ .Values.settings.tls.caFile | quote }}
            - name: OTLP_TLS_CERT_FILE
              value: {{ .Values.settings.tls.certFile | quote }}
            - name: OTLP_TLS_KEY_FILE
              value: {{ .Values.settings.tls.keyFile | quote }}
            - name: OTLP_CERTIFICATE_RELOAD_INTERVAL
              value: {{ .Values.settings.tls.reloadInterval | quote }}
            # TLS KEDA
            - name: KEDA_TLS_ENABLED
              value: {{ .Values.settings.tls.keda.enabled | quote }}
            - name: KEDA_TLS_CERT_FILE
              value: {{ .Values.settings.tls.keda.certFile | default .Values.settings.tls.certFile | quote }}
            - name: KEDA_TLS_KEY_FILE
              value: {{ .Values.settings.tls.keda.keyFile | default .Values.settings.tls.keyFile | quote }}
      {{- if .Values.settings.logs.noColor }}
            - name: NO_COLOR
              value: {{ .Values.settings.logs.noColor | quote }}
      {{- end }}
      {{- if .Values.settings.logs.noBanner }}
            - name: NO_BANNER
              value: {{ .Values.settings.logs.noBanner | quote }}
      {{- end }}
          args:
            - --zap-log-level={{ .Values.settings.logs.logLvl }}
            - --zap-stacktrace-level={{ .Values.settings.logs.stackTracesLvl }}
          livenessProbe:
            httpGet:
              port: {{ .Values.settings.restApiPort }}
              path: /info
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              port: {{ .Values.settings.restApiPort }}
              path: /info
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.volumeMounts .Values.settings.tls.secrets }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- range .Values.settings.tls.secrets }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
              readOnly: true
          {{- end }}
          {{- end }}
      {{- if or .Values.volumes .Values.settings.tls.secrets }}
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
          {{- range .Values.settings.tls.secrets }}
        - name: {{ .name }}
          secret:
            defaultMode: 420
            secretName: {{ .name }}
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
