{{- if .Values.validatingAdmissionPolicy.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ .Values.validatingAdmissionPolicy.name }}
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups:   ["keda.sh"]
        apiVersions: ["v1alpha1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["scaledobjects"]
  variables:
    - name: otelScalersWithSugar
      expression: "object.spec.triggers.filter(t, t.type == 'kedify-otel')"
    - name: otelScalersNoSugar
      expression: "object.spec.triggers.filter(t, t.type == 'external' && has(t.metadata.scalerAddress) && t.metadata.scalerAddress.contains('otel'))"
    - name: triggers
      expression: "variables.otelScalersWithSugar + variables.otelScalersNoSugar"
    - name: allowedOperationsOverTime
      expression: "['avg', 'count', 'last_one', 'min', 'max', 'rate', 'sum']"
  validations:
    - expression: "variables.triggers.size() > 0 && variables.triggers.all(t, has(t.metadata.targetValue))"
      messageExpression: "'Missing \\'targetValue\\' on ScaledObject\\' otel trigger: ' + object.metadata.name"
    - expression: "variables.triggers.size() > 0 && variables.triggers.all(t, !has(t.metadata.operationOverTime) || t.metadata.operationOverTime in variables.allowedOperationsOverTime)"
      messageExpression: "'Malformed trigger in ScaledObject: ' + object.metadata.name + ' unsupported operationOverTime: ' + variables.triggers.filter(t, has(t.metadata.operationOverTime) && !(t.metadata.operationOverTime in variables.allowedOperationsOverTime))[0].metadata.operationOverTime"
    - expression: "variables.triggers.size() > 0 && variables.triggers.all(t, has(t.metadata.metricQuery) && t.metadata.metricQuery.matches('^((sum|avg|min|max|count)\\\\()?[a-zA-Z][a-zA-Z0-9-_]*(\\\\{[^,=]+=[^,=]+(,[^,=]+=[^,=]+)*?\\\\})?\\\\)?$'))"
      messageExpression: "'Malformed trigger in ScaledObject: ' + object.metadata.name + ' unsupported metricQuery: ' + variables.triggers.filter(t, !has(t.metadata.metricQuery) || !t.metadata.metricQuery.matches('^((sum|avg|min|max|count)\\\\()?[a-zA-Z][a-zA-Z0-9-_]*(\\\\{[^,=]+=[^,=]+(,[^,=]+=[^,=]+)*?\\\\})?\\\\)?$'))[0].metadata.metricQuery"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "{{ .Values.validatingAdmissionPolicy.name }}-binding"
spec:
  policyName: "well-formed-otel-scalers"
  validationActions: [Deny]
{{- end }}
