# helm upgrade -i keda-otel-scaler oci://ghcr.io/kedify/charts/otel-add-on -nkeda --version=v0.0.11 -f ./dcgm-values.yaml
settings:
  metricStore:
    retentionSeconds: 60
  # logs:
  #   logLvl: debug

otelOperator:
  enabled: true
  # manager:
  #   extraArgs:
  #   - --zap-log-level=debug

otelOperatorCrs:
- name: vllm-metrics
  enabled: true
  debug: true
  mode: deployment
  namespace: keda
  alternateOtelConfig:
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            static_configs:
            - targets: [ 'nvidia-dcgm-exporter.gpu-operator.svc:9400' ]
    processors:
      transform:
        metric_statements:
          - context: datapoint
            statements:
              - set(datapoint.attributes["svc"], datapoint.attributes["exported_pod"])
              - replace_pattern(datapoint.attributes["svc"], "(.*)-[^-]+-[^-]+", "$1")
      filter/metrics:
        metrics:
          include:
            match_type: strict
            metric_names:
              - DCGM_FI_DEV_MEM_COPY_UTIL
              # - DCGM_FI_DEV_GPU_UTIL
    exporters:
      otlp/keda:
        endpoint: keda-otel-scaler.keda.svc:4317
        compression: "none"
        tls:
          insecure: true
      debug:
        verbosity: detailed
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [filter/metrics, transform]
          exporters: [debug, otlp/keda]
