apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: model-dcgm
  annotations:
    autoscaling.keda.sh/paused: "false"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llama
  triggers:
    - type: external
      metadata:
        scalerAddress: "keda-otel-scaler.keda.svc:4318"
        # 'svc' dimension is added by OTel processor (transform)
        metricQuery: "sum(DCGM_FI_DEV_MEM_COPY_UTIL{svc=llama})"
        operationOverTime: "avg"
        targetValue: "40"
  minReplicaCount: 1
  maxReplicaCount: 2
  fallback:
    failureThreshold: 10
    replicas: 1
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          # this should be higher in prod
          stabilizationWindowSeconds: 1200
        scaleUp:
          # this should be much higher in prod
          stabilizationWindowSeconds: 1
