apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dapr-nodeapp
spec:
  scaleTargetRef:
    name: nodeapp
  triggers:
    - type: kedify-otel
      metadata:
        scalerAddress: 'keda-otel-scaler.keda.svc:4318'
        metricQuery: 'sum(runtime_service_invocation_req_recv_total{app_id="nodeapp",src_app_id="pythonapp"})'
        operationOverTime: 'rate'
        targetValue: '1'
        clampMax: '10'
    - type: kedify-otel
      metadata:
        scalerAddress: 'keda-otel-scaler.keda.svc:4318'
        metricQuery: 'sum(http_server_response_count{app_id="pythonapp",method="POST",path="/neworder/",status="500"})'
        operationOverTime: 'rate'
        targetValue: '1'
        clampMax: '1'
  minReplicaCount: 0
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 15
