name: 'PR checks'
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  go-build-test:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
      checks: write  # Optional: Allow write access to checks to allow the golangci/golangci-lint-action to annotate code in the PR (SARIF)

    name: Inspect packages
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Verify dependencies
        run: |
          go mod verify
          go mod tidy
          gofmt -s -w .
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "dirty repository"
            git status
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          skip-cache: true

      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
          staticcheck ./...

      - name: Run vulncheck
        run: |
          echo -e "### vulncheck\n\n" >> ${GITHUB_STEP_SUMMARY}
          echo '```' >> ${GITHUB_STEP_SUMMARY}
          go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
          (govulncheck ./... || true) | tee -a ${GITHUB_STEP_SUMMARY}
          echo '```' >> ${GITHUB_STEP_SUMMARY}

      - name: Build
        env:
          CGO_ENABLED: 0
        run: make build

      - name: Test
        run: make test

  build-and-publish-images:
    needs: [ go-build-test ]
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    secrets: inherit
    uses: ./.github/workflows/release-image.yaml
    with:
      tag: pr-${{ github.event.pull_request.number }}
      releaseWithGoReleaser: false

  run-e2e-tests:
    needs: [ build-and-publish-images ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run the end to end tests
        env:
          OTEL_SCALER_VERSION: pr-${{ github.event.pull_request.number }}
          PR_BRANCH: ${{ github.head_ref }}
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          E2E_PRINT_LOGS: "true"
        run: make e2e-test
